# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['MAPseq_Wizard_2.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('sample_data', 'sample_data'),
        ('helpers', 'helpers'),
        ('process-nbcm-tsv.py', '.'),
        ('requirements.txt', '.'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.filedialog',
        'tkinter.messagebox',
        'tkinter.scrolledtext',
        'numpy',
        'pandas',
        'matplotlib',
        'scipy',
        'sklearn',
        'seaborn',
        'sympy',
        'adjustText',
        'upsetplot',
        'statsmodels',
        'networkx',
        'regex',
        'argparse',
        'subprocess',
        'os',
        'sys',
        'json',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MAPseq_Wizard_2',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
