"""
Command generator for MAPseq Pipeline Wizard
Generates all_commands.txt style files from configuration
"""

from pathlib import Path
from typing import List, Dict, Any
from .config_manager import ConfigManager
from .utils.path_utils import normalize_path, get_repo_root


class CommandGenerator:
    """Generates command files from configuration"""
    
    def __init__(self, config_manager: ConfigManager):
        """
        Initialize CommandGenerator
        
        Args:
            config_manager: ConfigManager instance with loaded configuration
        """
        self.config = config_manager
        self.repo_root = Path(get_repo_root())
    
    def generate_all_commands(self, output_path: Path) -> None:
        """
        Generate complete command file from configuration
        
        Args:
            output_path: Path to save the generated command file
        """
        commands = []
        
        # Add header
        commands.append("# ============================================================================")
        commands.append("# MAPseq Processing Pipeline - Generated by MAPseq Wizard")
        commands.append("# ============================================================================")
        commands.append("")
        
        # Generate preprocessing commands for all cohorts
        preprocess_commands = self.generate_preprocessing_commands(output_path.parent)
        if preprocess_commands:
            commands.append("# ============================================================================")
            commands.append("# Preprocessing Commands")
            commands.append("# ============================================================================")
            commands.append("")
            commands.extend(preprocess_commands)
            commands.append("")
        
        # Generate commands for each parameterization
        parameterizations = self.config.get('main_processing.parameterizations', [])
        
        for param in parameterizations:
            commands.extend(self._generate_parameterization_commands(param))
            commands.append("")
        
        # Write to file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(commands))
    
    def _generate_parameterization_commands(self, param: Dict[str, Any]) -> List[str]:
        """Generate commands for a single parameterization"""
        commands = []
        param_name = param['name']
        
        # Parameterization header
        commands.append("# ============================================================================")
        commands.append(f"# Parameterization: {param_name}")
        commands.append("# ============================================================================")
        commands.append("")
        
        # Main processing commands for each age group
        age_groups = self.config.get('main_processing.age_groups', {})
        
        for age_group, age_data in age_groups.items():
            samples = age_data.get('samples', [])
            if not samples:
                continue
            
            commands.append(f"# Main Processing: {age_group}/{param_name}")
            
            for sample in samples:
                cmd = self._generate_main_processing_command(
                    age_group, param_name, sample, param
                )
                commands.append(cmd)
            commands.append("")
        
        # Helper scripts (run once per parameterization, cross-age)
        helper_scripts = self.config.get('helper_scripts', {})
        if helper_scripts.get('enabled'):
            commands.append(f"# Helper Scripts for {param_name} (cross-age analysis)")
            commands.append("# Note: Helpers are run once per parameterization and will find data from all ages")
            commands.append("")
            
            commands.extend(self._generate_helper_script_commands(param_name, helper_scripts))
            commands.append("")
        
        # Quality control
        qc_config = self.config.get('quality_control', {})
        if qc_config.get('enabled'):
            commands.append(f"# Quality Control for {param_name}")
            qc_cmd = self._generate_qc_command(param_name, qc_config)
            if qc_cmd:
                commands.append(qc_cmd)
            commands.append("")
        
        return commands
    
    def _generate_main_processing_command(self, age_group: str, param_name: str,
                                         sample: Dict[str, Any], param: Dict[str, Any]) -> str:
        """Generate a single main processing command"""
        base_output_dir = self.config.get('project.base_output_dir', '02_output')
        output_dir = Path(base_output_dir) / age_group / param_name
        
        sample_name = sample['name']
        data_file = sample['data_file']
        labels = sample['labels']
        
        # Build command
        cmd_parts = [
            "python", str(self.repo_root / "process-nbcm-tsv.py"),
            "-o", str(output_dir.resolve()),
            "-s", sample_name,
            "-d", str(Path(data_file).resolve()),
            "-i", str(param['injection_umi_min']),
            "-r", str(param['min_body_to_target_ratio']),
            "-t", str(param['min_target_count']),
            "-u", str(param['target_umi_min']),
            "-l", f'"{labels}"',
        ]
        
        # Add optional flags
        if param.get('force_user_threshold'):
            cmd_parts.append("--force_user_threshold")
        
        # Add alpha if specified (default is 0.05)
        alpha = self.config.get('main_processing.alpha', 0.05)
        if alpha != 0.05:
            cmd_parts.extend(["-a", str(alpha)])
        
        return " ".join(cmd_parts)
    
    def _generate_helper_script_commands(self, param_name: str,
                                        helper_config: Dict[str, Any]) -> List[str]:
        """Generate helper script commands with proper dependency ordering"""
        commands = []
        base_output_dir = Path(helper_config.get('base_output_dir', '02_output'))
        helper_output_base = base_output_dir / f"{param_name}_helpers"
        
        enabled = helper_config.get('enabled', [])
        
        # Script 01: Motif analysis per animal
        if '01' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '01_motif_analysis_per_animal.py'} "
                f"--base_output_dir {base_output_dir.resolve()} "
                f"--helper_output_dir {helper_output_base / '01_motif_analysis_per_animal'} "
                f"--output_mode both"
            )
            commands.append(cmd)
        
        # Script 02: Projection analysis
        if '02' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '02_projection_analysis.py'} "
                f"--base_output_dir {base_output_dir.resolve()} "
                f"--helper_output_dir {helper_output_base / '02_projection_analysis'}"
            )
            commands.append(cmd)
        
        # Script 03: Composition
        if '03' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '03_composition.py'} "
                f"--base_output_dir {base_output_dir.resolve()} "
                f"--helper_output_dir {helper_output_base / '03_composition'}"
            )
            commands.append(cmd)
        
        # Script 04: Proportions over time
        if '04' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '04_proportions_over_time_stats.py'} "
                f"--base_output_dir {base_output_dir.resolve()} "
                f"--helper_output_dir {helper_output_base / '04_proportions_over_time_stats'}"
            )
            commands.append(cmd)
        
        # Script 05: Motif analysis (required for 06 and 07)
        if '05' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '05_motif_analysis.py'} "
                f"--base_output_dir {base_output_dir.resolve()} "
                f"--helper_output_dir {helper_output_base / '05_motif_analysis'}"
            )
            commands.append(cmd)
        
        # Script 06: Motif divergence (requires 05)
        if '06' in enabled and '05' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '06_all_motif_divergence.py'} "
                f"--input_dir {helper_output_base / '05_motif_analysis'} "
                f"--helper_output_dir {helper_output_base / '06_all_motif_divergence'}"
            )
            commands.append(cmd)
        
        # Script 07: Motif significance trajectories (requires 05)
        if '07' in enabled and '05' in enabled:
            # First, copy upsetplot files
            input_dir = helper_output_base / '07_input'
            commands.append(f"mkdir -p {input_dir.resolve()}")
            
            # Find and copy upsetplot files
            find_cmd = (
                f"find {base_output_dir.resolve()} -type f "
                f"\\( -path '*/{param_name}/analysis/*_ALL_*_filters_upsetplot.csv' "
                f"-o -path '*/{param_name}/analysis/*_alL_*_filters_upsetplot.csv' \\) "
                f"| xargs -I {{}} cp {{}} {input_dir.resolve()}/"
            )
            commands.append(find_cmd)
            
            # Then run the script
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '07_motif_significange_trajectories.py'} "
                f"--input_dir {input_dir.resolve()} "
                f"--helper_output_dir {helper_output_base / '07_motif_significange_trajectories'}"
            )
            commands.append(cmd)
        
        # Script 08: Motif clustering (requires 07)
        if '08' in enabled and '07' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '08_motif_clustering.py'} "
                f"--input_dir {helper_output_base / '07_motif_significange_trajectories'} "
                f"--helper_output_dir {helper_output_base / '08_motif_clustering'}"
            )
            commands.append(cmd)
        
        # Script 09: Plot normalized projection strength
        if '09' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '09_plot_normalized_projection_strength_data.py'} "
                f"{base_output_dir.resolve()} "
                f"--output_dir {helper_output_base / '09_plot_normalized_projection_strength_data'} "
                f"--file_type aggregate "
                f"--all_ages_base_dir {base_output_dir.resolve()}"
            )
            commands.append(cmd)
        
        # Script 13: Aggregate projection summaries
        if '13' in enabled:
            cmd = (
                f"python {self.repo_root / 'helpers' / 'scripts' / '13_aggregate_projection_summaries.py'} "
                f"--base_dir {base_output_dir.resolve()} "
                f"--parameterization {param_name}"
            )
            commands.append(cmd)
        
        return commands
    
    def _generate_qc_command(self, param_name: str, qc_config: Dict[str, Any]) -> str:
        """Generate quality control command"""
        base_output_dir = Path(qc_config.get('base_output_dir', '02_output'))
        repo_root = self.repo_root
        
        # Find first age group with this parameterization
        age_groups = self.config.get('main_processing.age_groups', {})
        first_age = None
        for age_group in ['p3', 'p12', 'p20', 'p60']:
            if age_group in age_groups:
                first_age = age_group
                break
        
        if not first_age:
            return ""
        
        output_file = base_output_dir / f"{param_name}_qc_report.txt"
        
        cmd = (
            f"python {repo_root / 'postprocessing_checks.py'} "
            f"--repo_root {repo_root.resolve()} "
            f"--base_output_dir {base_output_dir.resolve() / first_age / param_name} "
            f"--output {output_file.resolve()}"
        )
        
        return cmd
    
    def generate_preprocessing_commands(self, output_dir: Path) -> List[str]:
        """Generate preprocessing commands for all cohorts"""
        commands = []
        preprocess_config = self.config.get('preprocessing', {})
        cohorts = preprocess_config.get('cohorts', {})
        
        if not cohorts:
            # Legacy format: single preprocessing
            input_dir = preprocess_config.get('input_dir', '')
            output_dir_single = preprocess_config.get('output_dir', '')
            fallback_threshold = preprocess_config.get('fallback_threshold', 2.0)
            
            if input_dir:
                # Generate mapping file path
                mapping_file = output_dir / "preprocessing_mappings.yaml"
                self._save_preprocessing_mappings(mapping_file, preprocess_config)
                
                cmd_parts = [
                    "python", str(self.repo_root / "preprocess_and_aggregate.py"),
                    "-i", str(Path(input_dir).resolve()),
                    "-o", str(Path(output_dir_single).resolve()),
                    "-t", str(fallback_threshold),
                    "--mapping-file", str(mapping_file.resolve()),
                ]
                commands.append(" ".join(cmd_parts))
        else:
            # New format: multiple cohorts
            for cohort_name, cohort_data in cohorts.items():
                input_dir = cohort_data.get('input_dir', '')
                cohort_output_dir = cohort_data.get('output_dir', '')
                fallback_threshold = cohort_data.get('fallback_threshold', 2.0)
                
                if not input_dir or not cohort_output_dir:
                    continue
                
                # Generate mapping file for this cohort
                mapping_file = output_dir / f"preprocessing_mappings_{cohort_name}.yaml"
                self._save_cohort_mappings(mapping_file, cohort_data)
                
                cmd_parts = [
                    "python", str(self.repo_root / "preprocess_and_aggregate.py"),
                    "-i", str(Path(input_dir).resolve()),
                    "-o", str(Path(cohort_output_dir).resolve()),
                    "-t", str(fallback_threshold),
                    "--mapping-file", str(mapping_file.resolve()),
                ]
                commands.append(f"# Preprocessing for cohort: {cohort_name}")
                commands.append(" ".join(cmd_parts))
                commands.append("")
        
        return commands
    
    def _save_preprocessing_mappings(self, mapping_file: Path, preprocess_config: dict):
        """Save preprocessing mappings to YAML file"""
        import yaml
        mapping_data = {
            'column_mappings': preprocess_config.get('column_mappings', {}),
            'negative_columns': preprocess_config.get('negative_columns', {}),
        }
        mapping_file.parent.mkdir(parents=True, exist_ok=True)
        with open(mapping_file, 'w', encoding='utf-8') as f:
            yaml.dump(mapping_data, f, default_flow_style=False)
    
    def _save_cohort_mappings(self, mapping_file: Path, cohort_data: dict):
        """Save cohort mappings to YAML file"""
        import yaml
        mapping_data = {
            'column_mappings': cohort_data.get('column_mappings', {}),
            'negative_columns': cohort_data.get('negative_columns', {}),
        }
        mapping_file.parent.mkdir(parents=True, exist_ok=True)
        with open(mapping_file, 'w', encoding='utf-8') as f:
            yaml.dump(mapping_data, f, default_flow_style=False)
    
    def generate_figure_generation_command(self) -> str:
        """Generate figure generation command"""
        fig_config = self.config.get('figure_generation', {})
        if not fig_config.get('enabled'):
            return ""
        
        param_name = fig_config.get('parameterization', '')
        output_dir = Path(fig_config.get('output_dir', ''))
        
        cmd_parts = [
            "python", str(self.repo_root / "figure_generation" / "generate_figure_from_outputs.py"),
        ]
        
        if param_name:
            cmd_parts.extend(["--parameterization", param_name])
        
        if output_dir:
            cmd_parts.extend(["--output_dir", str(output_dir.resolve())])
        
        return " ".join(cmd_parts)
